name: Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - name: Run composer install
        run: composer install
      - name: Run npm install
        run: npm install
      - name: Run npm run dev
        run: npm run dev
      - name: Create .env
        run: cp .env.example .env
      - name: Create app key
        run: php artisan key:generate
      - name: Stop mysql service
        run: sudo systemctl stop mysql
      - name: Remove privileges
        run: mysqld_safe
      - name: Create data base
        run: mysql -u root -e 'CREATE DATABASE IF NOT EXISTS laravel;'
      - name: Run migrations
        run: php artisan migrate
      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          APP_ENV: testing
